services:
  node-app:
    build: .
    ports:
      - "4000:4000"
    env_file:
      - ./.env
    depends_on:
      - postgressdbByMarwa
      - mongoByMarwa

  mongoByMarwa:
    image: mongo
    restart: always
    volumes:
      - mongo-db-by-marwa:/data/db
    environment:
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: example

  
  mongo-express:
    image: mongo-express
    restart: always
    ports:
      - 8081:8081
    environment:
      ME_CONFIG_MONGODB_URL: mongodb://root:example@mongoByMarwa:27017/
      ME_CONFIG_BASICAUTH_ENABLED: true
      ME_CONFIG_BASICAUTH_USERNAME: mongoexpressuser
      ME_CONFIG_BASICAUTH_PASSWORD: mongoexpresspass
    depends_on:
      - mongoByMarwa

  redisByMarwa:
    image: "redis"
    container_name: "redis-by-marwa"
    ports:
      - "6379:6379"
    depends_on:
      - node-app

  nginx-by-marwa:
    image: nginx:latest
    container_name: nginx-by-marwa
    ports:
      - "8080:80"
    depends_on:
      - node-app
    volumes:
      - ./nginx/default.conf:/etc/nginx/conf.d/default.conf:ro

  postgressdbByMarwa:
    image: postgres
    restart: always
    # set shared memory limit when using docker compose
    shm_size: 128mb
    # or set shared memory limit when deploy via swarm stack
    #volumes:
    #  - type: tmpfs
    #    target: /dev/shm
    #    tmpfs:
    #      size: 134217728 # 128*2^20 bytes = 128Mb
    volumes:
      - pgdata-by-marwa:/var/lib/postgresql
    environment:
      POSTGRES_USER: userexample
      POSTGRES_PASSWORD: example
      
volumes:
  mongo-db-by-marwa:
  pgdata-by-marwa:
